# Introducción a Numpy

In [246]:
import sys
import numpy as np

## Creación de Arrays

Los arrays son ligeramente diferentes a las listas.

### Arrays 1-Dimensionales

#### Cositas comunes

In [308]:
# Creación de un array con enteros en su interior:

array_1D_int = np.array([1, 2, 3, 4])

In [248]:
array_1D_int

array([1, 2, 3, 4])

In [249]:
print(array_1D_int)

[1 2 3 4]


In [250]:
type(array_1D_int)

numpy.ndarray

In [251]:
# Conocer la dimensión del array:

array_1D_int.ndim

1

In [438]:
# Conocer el número de elementos dentros del array 1-Dimensional (4 maneras):

print( array_1D_int.shape )
print( array_1D_int.shape[0] )
print( len(array_1D_int) )
print( array_1D.size )


(4,)
4
4
4


In [457]:
# Acceder a los elementos internos de un array:
#
# (Muy similar a la listas)

print( array_1D_int[2] )
print( array_1D_int[2:] )
print( array_1D_int[:-1] )
print( array_1D_int[:2] )
print( array_1D_int[-1] )
print( array_1D_int[1:3] )

3
[3 4]
[1 2 3]
[1 2]
4
[2 3]


In [460]:
# Iterar sobre elementos de un array:

for num in array_1D_int:
    print(num+1)

2
3
4
5


In [523]:
# Iteración "pretty"

np.array([num+3 for num in array_1D_int])

array([4, 5, 6, 7])

#### Algunos métodos interesantes en array 1-Dimensionales

In [306]:
# Conocer el tipo de variable que almacena el array:

array_1D_int.dtype

dtype('int32')

In [309]:
array_1D_int

array([1, 2, 3, 4])

In [316]:
# Para un array
#
# [x1, x2, x3, ···, xn]
#
# de n elementos.
#
# El método .sum() devuelve la suma x1+x2+x3+···+xn
#
# El método .prod() devuelve el producto x1*x2*x3*···*xn
#
# El método .cumsum() devuelve un array de n elementos [x1, x1+x2, x1+x2+x3, ···, x1+x2+···+xn]
#
# El método .cumprod() devuelve un array de n elementos [x1, x1*x2, x1*x2*x3, ···, x1*x2*···*xn]

print( "    .sum(): ", array_1D_int.sum() )
print( "   .prod(): ", array_1D_int.prod() )
print( " .cumsum(): ",array_1D_int.cumsum() )
print( ".cumprod(): ",array_1D_int.cumprod() )

    .sum():  10
   .prod():  24
 .cumsum():  [ 1  3  6 10]
.cumprod():  [ 1  2  6 24]


In [333]:
# Para un array
#
# [x1, x2, x3, ···, xn]
#
# de n elementos.
#
# El método .max() devuelve el máximo de los elementos x1 ··· xn
#
# El método .min() devuelve el mínimo de los elementos x1 ··· xn
#
# El método .mean() devuelve la media de los n elementos (x1+x2+···+xn)/n
#
# El método .std() devuelve la desv. estandar de los n elementos.

print( "  .max(): ", array_1D_int.max() )
print( "  .min(): ", array_1D_int.min() )
print( " .mean(): ", array_1D_int.mean() )
print( "  .std(): ", array_1D_int.std() )

  .max():  4
  .min():  1
 .mean():  2.5
  .std():  1.118033988749895


In [334]:
# Para un array
#
# [x1, x2, x3, ···, xn]
#
# de n elementos.
#
# El método .repeat(m), siendo m un número entero, devuelve un un array de n*m elementos de la forma:
#
# [x1, x1, ···, x1, x2, x2, ···, x2, x3, x3, ···, x3, ··· , xn, xn, ···, xn]
# (- x1 m veces -) (- x2 m veces -) (- x3 m veces -)  ···   (- xn m veces -)
#  
array_1D_int.repeat(2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [374]:
# Redimensionar un array 1-Dimensional de n elementos a un array de mayor dimensionalidad (i x j)
#
#
# IMPORTANTE!! El producto i x j deberá ser igual a n.

print("El array {} tiene 1 dimensión y {} elementos".format(array_1D_int,array_1D_int.size))
print("Redimensionandolo a un array de 2x2 = {} queda:\n".format(array_1D_int.size))
print(array_1D_int.reshape(2,2))


El array [1 2 3 4] tiene 1 dimensión y 4 elementos
Redimensionandolo a un array de 2x2 = 4 queda:

[[1 2]
 [3 4]]


In [387]:
# Redondear los elementos float de un array a un número de decimales 'd'
#

d = 1

array_1D_float = np.array([1.1111, 2.2222, 3.3333, 4.4444, 5.5555])
print("                    Array Original: ", array_1D_float)
print("Array Redondeado a 1 cifra decimal: ", array_1D_float.round(1))

                    Array Original:  [1.1111 2.2222 3.3333 4.4444 5.5555]
Array Redondeado a 1 cifra decimal:  [1.1 2.2 3.3 4.4 5.6]


In [417]:
# Ordenación de los elementos de un array --> Igual que las listas!
#
# .sorted(array_to_sort) --> conserva invariable el array original.
# array_to_sort.sort()   --> modifica el array ordenándolo
#
# Por defecto se ordena de modo ascendente. Para modificar a modo descendente --> reverse=True

array_1D_int_2 = [12,8,90,5,32]
print("                                        Array Original (array_1D_int_2) --> ",array_1D_int_2)
array_1D_int_2_sorted = sorted(array_1D_int_2, reverse=True)
print("Ejecutamos array_1D_int_2_sorted = sorted(array_1D_int_2, reverse=True)")
print("                                                  array_1D_int_2_sorted --> ",array_1D_int_2_sorted)
print("                                                         array_1D_int_2 --> ",array_1D_int_2)
array_1D_int_2.sort()
print("                                       Ejecutamos array_1D_int_2.sort()")
print("                                                  array_1D_int_2_sorted --> ",array_1D_int_2_sorted)
print("                                                         array_1D_int_2 --> ",array_1D_int_2)


                                        Array Original (array_1D_int_2) -->  [12, 8, 90, 5, 32]
Ejecutamos array_1D_int_2_sorted = sorted(array_1D_int_2, reverse=True)
                                                  array_1D_int_2_sorted -->  [90, 32, 12, 8, 5]
                                                         array_1D_int_2 -->  [12, 8, 90, 5, 32]
                                       Ejecutamos array_1D_int_2.sort()
                                                  array_1D_int_2_sorted -->  [90, 32, 12, 8, 5]
                                                         array_1D_int_2 -->  [5, 8, 12, 32, 90]


In [285]:
# Rellenar todas las posiciones de un array con un mismo valor:
#
# IMPORTANTE! Sólo podrán rellenarse con valores de la misma clase que la del array a rellenar!!!

array_1D_int = np.array([1, 2, 3, 4])
print("Elementos en array son de tipo: ",array_1D_int.dtype)
print("Array creado como:              ", array_1D_int)
array_1D_int.fill(8)
print("Array tras uso de .fill(8): ", array_1D_int)

Elementos en array son de tipo:  int32
Array creado como:               [1 2 3 4]
Array tras uso de .fill(8):  [8 8 8 8]


In [260]:
# Creación de un array de strings y posterior relleno con un mismo string:
#
#
# IMPORTANTE!! Aunque inicialmente haya creado el array con solo strings, Numpy lo crea como tipo 'mixto' --> '<U1'

array_1D_str = np.array(["a", "b", "c"])
print("Array creado como:            ", array_1D_str)
print("Elementos en array son de tipo: ",array_1D_str.dtype)
array_1D_str.fill("d")
print("Array tras uso de .fill(\"d\"): ", array_1D_str)

Array creado como:             ['a' 'b' 'c']
Elementos en array son de tipo:  <U1
Array tras uso de .fill("d"):  ['d' 'd' 'd']


In [261]:
# Creación de un array de float y posterior relleno con un mismo float:

array_1D_float = np.array([1.1, 2.2, 3.3])
print("Array creado como:              ", array_1D_float)
print("Elementos en array son de tipo: ",array_1D_float.dtype)
array_1D_float.fill(4.4)
print("Array tras uso de .fill(4.4):   ", array_1D_float)

Array creado como:               [1.1 2.2 3.3]
Elementos en array son de tipo:  float64
Array tras uso de .fill(4.4):    [4.4 4.4 4.4]


In [268]:
# Creación de un array mixto y posterior relleno con un mismo entero:
#
#

array_1D_mix = np.array(["a", 2, 3, "d"])
print("Array creado como:              ", array_1D_mix)
print("Elementos en array son de tipo: ",array_1D_mix.dtype)
array_1D_mix.fill(4)
print("Array tras uso de .fill(4):   ", array_1D_mix)
print("El array no se crea con enteros... :(")

Array creado como:               ['a' '2' '3' 'd']
Elementos en array son de tipo:  <U1
Array tras uso de .fill(4):    ['4' '4' '4' '4']
El array no se crea con enteros... :(


In [290]:
# Devuelve los índices dentro del array de aquellos elementos del array que son distions de 0:

print("Para el array {}, los IDs de los elementos que no son 0 son {}".format(
                                                                               array_1D_int,
                                                                               array_1D_int.nonzero()
                                                                             ))
print("Para el array {}, los IDs de los elementos que no son 0 son {}".format(
                                                                               np.array([2,0,2,0]),
                                                                               np.array([2,0,2,0]).nonzero()
                                                                             ))


Para el array [8 8 8 8], los IDs de los elementos que no son 0 son (array([0, 1, 2, 3], dtype=int64),)
Para el array [2 0 2 0], los IDs de los elementos que no son 0 son (array([0, 2], dtype=int64),)


### Arrays N-Dimensionales (aka matrices)

#### Cositas Comunes

In [467]:
# Creación de una matriz (array de más de 1 dimensión) con enteros en su interior:

matriz = np.array([
                    [1,3,5],
                    [2,4,6]
])

In [110]:
matriz

array([[1, 3, 5],
       [2, 4, 6]])

In [111]:
print(matriz)

[[1 3 5]
 [2 4 6]]


In [112]:
type(matriz)

numpy.ndarray

In [113]:
# Conocer la dimensión del array (de la matriz):

matriz.ndim

2

In [114]:
# Conocer la forma de la matriz
#
#
# Devuelve:
#
# (num_de_filas, num_de_columnas)

matriz.shape

(2, 3)

In [115]:
# Forma alternativa de conocer el número de filas en la matriz:

len(matriz)

2

In [150]:
# Conocer el número TOTAL de elementos dentro de la matriz (2 maneras):

print( matriz.size )
print( matriz.shape[0]*matriz.shape[1] )

6
6


In [621]:
# Acceder a los elementos internos de una matriz:
#
# (Muy similar a la listas)
#
# Para una matriz 'm x n':
#    · El acceso a una fila devuelve un array de shape (n x 1)
#    · El acceso a una columna devuelve un array de shape (m x 1) y no (1 x m)
#
# La sintaxis de acceso a un cierto elemento de la matriz es:
#
# matriz[ID_fila, ID_columna]
#
# IMPORTANTE RECORDAR!!! La 1ª fila/columna se indexa con 0!

print("Matriz:\n",matriz,"\n con shape: ",matriz.shape)
print("Primera Fila:\n",matriz[0],"\n con shape: ",matriz[0].shape)
print("Primera Fila:\n",matriz[0,:],"\n con shape: ",matriz[0,:].shape)
print("Primera Columna:\n",matriz[:,0],"\n con shape: ",matriz[:,0].shape)
print("El elemento en la segunda fila, tercera columna es: ",matriz[1,2])

Matriz:
 [[1 3 5]
 [2 4 6]] 
 con shape:  (2, 3)
Primera Fila:
 [1 3 5] 
 con shape:  (3,)
Primera Fila:
 [1 3 5] 
 con shape:  (3,)
Primera Columna:
 [1 2] 
 con shape:  (2,)
El elemento en la segunda fila, tercera columna es:  6


In [525]:
# Iteraciones sobre elementos matriciales

for fila in matriz:
    print("siguiente fila:")
    print(fila)
    

siguiente fila:
[1 3 5]
siguiente fila:
[2 4 6]


In [537]:
# Iteración Pretty

np.array([num*2 for num in matriz])

array([[ 2,  6, 10],
       [ 4,  8, 12]])

#### Otros métodos útiles con arrays N-dimensionales

In [573]:
# Conocer los tipos de los elementos contenidos en la matriz

matriz_int = np.array([[1,2,3],[4,5,6],[7,8,9]])
print( "Matriz de enteros:\n",matriz_int )
print( "Tipo Dato: ",matriz_int.dtype )


matriz_float = np.array([[1.1,2.2,3.3],[4.4,5.5,6.6],[7.7,8.8,9.9]])
print( "Matriz de floats:\n",matriz_float )
print( "Tipo Dato: ",matriz_float.dtype )

matriz_str = np.array([["a","b","c"],["d","e","f"],["h","i","j"]])
print( "Matriz de mixtos/str:\n",matriz_str )
print( "Tipo Dato: ",matriz_str.dtype )

matriz_bool = np.array([[True, True, True],[False,False,False]])
print( "Matriz de bools:\n",matriz_bool )
print( "Tipo Dato: ",matriz_bool.dtype )


Matriz de enteros:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tipo Dato:  int32
Matriz de floats:
 [[1.1 2.2 3.3]
 [4.4 5.5 6.6]
 [7.7 8.8 9.9]]
Tipo Dato:  float64
Matriz de mixtos/str:
 [['a' 'b' 'c']
 ['d' 'e' 'f']
 ['h' 'i' 'j']]
Tipo Dato:  <U1
Matriz de bools:
 [[ True  True  True]
 [False False False]]
Tipo Dato:  bool


In [582]:
# Para matrices con enteros y floats:

print( " Para matriz enteros:\n")
print( "    .sum(): ", matriz_int.sum() )
print( "   .prod(): ", matriz_int.prod() )
print( " .cumsum(): ", matriz_int.cumsum() )
print( ".cumprod(): ", matriz_int.cumprod(),"\n" )

print( " Para matriz floats:\n")
print( "    .sum(): ", matriz_float.sum() )
print( "   .prod(): ", matriz_float.prod() )
print( " .cumsum(): ", matriz_float.cumsum() )
print( ".cumprod(): ", matriz_float.cumprod() )

 Para matriz enteros:

    .sum():  45
   .prod():  362880
 .cumsum():  [ 1  3  6 10 15 21 28 36 45]
.cumprod():  [     1      2      6     24    120    720   5040  40320 362880] 

 Para matriz floats:

    .sum():  49.5
   .prod():  855652.0581100801
 .cumsum():  [ 1.1  3.3  6.6 11.  16.5 23.1 30.8 39.6 49.5]
.cumprod():  [1.10000000e+00 2.42000000e+00 7.98600000e+00 3.51384000e+01
 1.93261200e+02 1.27552392e+03 9.82153418e+03 8.64295008e+04
 8.55652058e+05]


In [607]:
# Valor max, min, mean, std:

print( "  .max(): ", matriz_int.max() )
print( "  .min(): ", matriz_int.min() )
print( " .mean(): ", matriz_int.mean() )
print( "  .std(): ", matriz_int.std() )

  .max():  9
  .min():  1
 .mean():  5.0
  .std():  2.581988897471611


**Obtención de las diagonales de las matrices (y de sus sumas):**
    
Se pueden obtener las diferentes diagonales de las matrices según el esquema del ejemplo abajo mostrado.

En matrices con elementos int o float se emplea el método .trace(d) para obtener la suma de los elementos de la diagonal d-esima.
    
<img src="./Images/matriz_diagonal.PNG" width="500"/>

In [882]:
# Obtener diagonales de las matrices:

matriz_diag = np.array([[1,4,7],[2,5,8],[3,6,9]])

print("Para la matriz:\n")
for fila in matriz_diag:
    print(fila)

print( "\nEl método .diagonal() o .diagonal(0) devuelve la diagonal principal de la matriz:",matriz_diag.diagonal() )
print( "El método .diagonal(-2) devuelve la diagonal 2ª por debajo de la diagonal ppal de la matriz:",matriz_diag.diagonal(-2) )
print( "El método .diagonal(1) devuelve la diagonal 1ª por encima de la diagonal ppal de la matriz:",matriz_diag.diagonal(1) )

print( "\nEl método .trace() o .trace(0) devuelve la suma de los elementos de la diagonal principal de la matriz:",matriz_diag.trace() )

Para la matriz:

[1 4 7]
[2 5 8]
[3 6 9]

El método .diagonal() o .diagonal(0) devuelve la diagonal principal de la matriz: [1 5 9]
El método .diagonal(-2) devuelve la diagonal 2ª por debajo de la diagonal ppal de la matriz: [3]
El método .diagonal(1) devuelve la diagonal 1ª por encima de la diagonal ppal de la matriz: [4 8]

El método .trace() o .trace(0) devuelve la suma de los elementos de la diagonal principal de la matriz: 15


In [636]:
# Rellenar con un cierto elemento:

matriz_int = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Para la matriz 'matriz_int':\n")
for fila in matriz_int:
    print(fila)
    
print("\nRelleno la primera fila de 4s usando: matriz_int[0,:].fill(4):\n")
matriz_int[0,:].fill(4)
for fila in matriz_int:
    print(fila)
    
print("\nRelleno toda matriz de 1s usando: matriz_int.fill(1):\n")
matriz_int.fill(1)
for fila in matriz_int:
    print(fila)
    
matriz_int = np.array([[1,2,3],[4,5,6],[7,8,9]])

Para la matriz 'matriz_int':

[1 2 3]
[4 5 6]
[7 8 9]

Relleno la primera fila de 4s usando: matriz_int[0,:].fill(4):

[4 4 4]
[4 5 6]
[7 8 9]

Relleno toda matriz de 1s usando: matriz_int.fill(1):

[1 1 1]
[1 1 1]
[1 1 1]


In [840]:
# Allanado / Alisado / Aplanado de matrices (flatten en inglés):
#
# Se trata de convertir arrays N-dimensionales en arrays 1-Dimensionales de tal manera que si se tiene una matriz de
# dimensiones n x m se obtenga un array de dimensiones 1 x n*m
#
matriz_int = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Para la matriz 'matriz_int':\n")
for fila in matriz_int:
    print(fila)
    
print("\nEl método .flatten() devuelve: ",matriz_int.flatten())
print("\nAnálogamente puede usarse el método .ravel()")

Para la matriz 'matriz_int':

[1 2 3]
[4 5 6]
[7 8 9]

El método .flatten() devuelve:  [1 2 3 4 5 6 7 8 9]

Análogamente puede usarse el método .ravel()


In [842]:
# Repetir los elementos de la matriz un n número de veces.
#
# IMPORTANTE: El método .repeat() devuelve un array 1-Dimensional (es decir, aplana la matriz)

matriz_int = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Para la matriz 'matriz_int':\n")
for fila in matriz_int:
    print(fila)
    
print("\nEl método .repeat(2) devuelve el array: ",matriz_int.repeat(2))

Para la matriz 'matriz_int':

[1 2 3]
[4 5 6]
[7 8 9]

El método .repeat(2) devuelve el array:  [1 1 2 2 3 3 4 4 5 5 6 6 7 7 8 8 9 9]


In [878]:
# Redimensionar una matriz de n elementos a un array de diferente dimensionalidad (i x j)
#
#
# IMPORTANTE!! El producto i x j deberá ser igual a n.

matriz_int_4x4 = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]])

print("Para la matriz:\n")
for fila in matriz_int_4x4:
    print(fila)
    
print("\nEl método .reshape(8,2) devuelve una matriz de 8 filas y 2 columnas:\n")
for fila in matriz_int_4x4.reshape(8,2):
    print(fila)

Para la matriz:

[1 1 1 1]
[2 2 2 2]
[3 3 3 3]
[4 4 4 4]

El método .reshape(8,2) devuelve una matriz de 8 filas y 2 columnas:

[1 1]
[1 1]
[2 2]
[2 2]
[3 3]
[3 3]
[4 4]
[4 4]


In [894]:
# Transponer matrices:

matriz_int_3x2 = np.array([[1,2,3],[4,5,6]])

print("Para la matriz:\n")
for fila in matriz_int_3x2:
    print(fila)
    
print("\nEl método .transpose o .T devuelve la matriz transpuesta:\n")
for fila in matriz_int_3x2.T:
    print(fila)



Para la matriz:

[1 2 3]
[4 5 6]

El método .transpose o .T devuelve la matriz transpuesta:

[1 4]
[2 5]
[3 6]


## Filtrado de Arrays

In [893]:
# Filtrado de elementos dentro de matrices / arrays:


matriz_int_3x2= np.array([[1, 4], [2, 4], [5, 0]])
print("Para la matriz:")
for fila in matriz_int_3x2:
    print(fila)

print("\nPodemos filtrar por aquellos elementos que sean mayor que 2 usando:")
print("\nidxs_fitrado = (matriz_int_3x2 >= 2)")
idxs_filtrado = (matriz_int_3x2 >= 2)

print("\nDevolviéndonos una matriz booleana:")
for fila in idxs_fitrado:
    print(fila)
    
print("\nEsta matriz se puede usar para indexar sobre la original\n(matriz_int_3x2[idxs_filtrado])\nde tal manera que nos devuelve los valores que cumplen la condición:")
print(matriz_int_3x2[idxs_filtrado])


Para la matriz:
[1 4]
[2 4]
[5 0]

Podemos filtrar por aquellos elementos que sean mayor que 2 usando:

idxs_fitrado = (matriz_int_3x2 >= 2)

Devolviéndonos una matriz booleana:
[False  True]
[ True  True]
[ True False]

Esta matriz se puede usar para indexar sobre la original
(matriz_int_3x2[idxs_filtrado])
de tal manera que nos devuelve los valores que cumplen la condición:
[4 2 4 5]


## Aritmética con Arrays

In [901]:
# Definimos las matrices:

M_1 = np.array([[10,20],[33,44]])
M_2 = np.array([[7,13],[0,23]])

In [960]:
# Ops básicas:

print("M_1:")
for fila in M_1:
    print(fila)

print("\nM_2:")
for fila in M_2:
    print(fila)
    
print("\n Suma elemento a elemento: M_1 + M_2:")
for fila in (M_1 + M_2):
    print(fila)
    
print("\n Producto elemento a elemento: M_1 * M_2:")
for fila in (M_1 * M_2):
    print(fila)
    
# IMPORTANTE!!!
#
# Recordar que los productos matriciales el número de columnas de M_1 deberás ser igual al número de filas de M_2 cuando
# se realice el M_1 x M_2
    
print("\n Producto matricial: M_1 @ M_2 o bien M_1.dot(M_2):")
for fila in (M_1 @ M_2):
    print(fila)

M_1:
[10 20]
[33 44]

M_2:
[ 7 13]
[ 0 23]

 Suma elemento a elemento: M_1 + M_2:
[17 33]
[33 67]

 Producto elemento a elemento: M_1 * M_2:
[ 70 260]
[   0 1012]

 Producto matricial: M_1 @ M_2 o bien M_1.dot(M_2):
[ 70 590]
[ 231 1441]


In [943]:
m_2x2 = np.array([[1,2],[3,4],[5,6]])
m_2x5 = np.array([[1,2,3,4,5],[3,4,5,6,7]])

(3, 2)
(2, 5)


In [958]:
print("Primera Matriz de tamaño {}:".format(m_2x2.shape))
for fila in m_2x2:
    print(fila)

print("\nSegunda Matriz de tamaño {}:".format(m_2x5.shape))
for fila in m_2x5:
    print(fila)

print("\nEl producto matricial da una matriz de tamaño {}:".format((m_2x2@m_2x5).shape))
for fila in (m_2x2@m_2x5):
    print(fila)

Primera Matriz de tamaño (3, 2):
[1 2]
[3 4]
[5 6]

Segunda Matriz de tamaño (2, 5):
[1 2 3 4 5]
[3 4 5 6 7]

El producto matricial da una matriz de tamaño (3, 5):
[ 7 10 13 16 19]
[15 22 29 36 43]
[23 34 45 56 67]
